// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./highlight.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "zQ]QPOOPbOPOOQ]QPOOOOQO'#Ca'#CaPOOO'#Ce'#CePOOO)C>X)C>XOOQO-E6_-E6_",
  stateData: "j~OWOSPPQQPQ~OSRO~OPSOQSO~O",
  goto: "dYPPPPPZPPPaQQORUQRTP",
  nodeNames: "⚠ LineComment BlockComment Program String",
  maxTerm: 9,
  propSources: [highlighting],
  skippedNodes: [0,1,2],
  repeatNodeCount: 1,
  tokenData: "%{~RXXYnYZn]^npqnrs!Pst#mxy$[!}#O$y#o#p%c~sSW~XYnYZn]^npqn~!SVOr!Prs!is#O!P#O#P!n#P;'S!P;'S;=`#g<%lO!P~!nOS~~!qRO;'S!P;'S;=`!z;=`O!P~!}WOr!Prs!is#O!P#O#P!n#P;'S!P;'S;=`#g;=`<%l!P<%lO!P~#jP;=`<%l!P~#pTOY#mYZ$PZ;'S#m;'S;=`$U<%lO#m~$UOP~~$XP;=`<%l#m~$_TOy$[yz$nz;'S$[;'S;=`$s<%lO$[~$sOQ~~$vP;=`<%l$[~$|TO#P$y#P#Q$n#Q;'S$y;'S;=`%]<%lO$y~%`P;=`<%l$y~%fTO#q%c#q#r$n#r;'S%c;'S;=`%u<%lO%c~%xP;=`<%l%c",
  tokenizers: [0],
  topRules: {"Program":[0,3]},
  tokenPrec: 0
})
