// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Listen = 1,
  To = 2,
  Burn = 3,
  The = 4,
  OutputToken = 5,
  LineComment = 6,
  BlockComment = 7,
  Program = 8,
  EOS = 9,
  VariableName = 10,
  EOB = 11,
  EOF = 12
