// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {Constant, Pronoun, output, listen, to} from "./tokens"
import {highlighting} from "./highlight.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$UQnQ!ZOOOuQ#mO'#CqO!dQTO'#CsOOQO'#Cd'#CdO!oQPO'#CwOOQ!Y'#Cp'#CpQYQ!ZOOQOQO'#Cj'#CjO!tQPOOO!yQPO'#CgO#OQPO,59]OOQ!Y'#Cv'#CvOOQ!Y,59_,59_O#TQUO,59cOOQ!Y-E6e-E6eOOQO-E6h-E6hOOQ!Y'#Ci'#CiO#cQ!ZO'#ChO#jQ!ZO,59ROOQ!Y1G.w1G.wOOQ!Y1G.}1G.}OOQ!Y-E6g-E6gOOQ!Y,59S,59SOOQ!Y-E6f-E6f",
  stateData: "$^~OROSSOS~OQRO`QOaPOfROhQOiQO~OYVO~PYObYOXeXQeX_eX`eXaeXfeXheXieX~OPZOUZOVZO~Ol]O~OYVO~OX`O~OfcO~OPZOUZOVZOmdO~OX`O~PYOX`OQZa_Za`ZaaZafZahZaiZa~OUVmRSXR~",
  goto: "!olPPPPPPPPmPPrx!O!VPPPPP!]!dP!dPP!i!dVSOUaQUOR^UQbXRgbSaXbReaQWOR_WSXOURfaVTOUaQ[QRd]",
  nodeNames: "⚠ Constant Pronoun LineComment BlockComment Program Number String VariableName EOS EOF",
  maxTerm: 29,
  propSources: [highlighting],
  skippedNodes: [0,3,4],
  repeatNodeCount: 4,
  tokenData: "4l~RlOY!yYZ#hZ]!y]^#o^r!yrs$Tst&[tx!yxy&vy!Q!y!Q![(}![!}!y!}#O)i#O#W!y#W#X+V#X#]!y#]#^-o#^#k!y#k#l.m#l#m2e#m#n2e#n#o!y#o#p2y#p;'S!y;'S;=`#b<%l~!y~O!y~~4gQ!|TOY!yYZ#]Z;'S!y;'S;=`#b<%lO!yQ#bOmQQ#eP;=`<%l!y~#oOmQX~~#tTX~OY!yYZ#]Z;'S!y;'S;=`#b<%lO!y~$WVOY$TYZ$mZr$Trs%ps;'S$T;'S;=`&U<%lO$T~$rTmQOr%Rrs%es;'S%R;'S;=`%j<%lO%R~%UTOr%Rrs%es;'S%R;'S;=`%j<%lO%R~%jOV~~%mP;=`<%l%R~%uTV~OY!yYZ#]Z;'S!y;'S;=`#b<%lO!y~&XP;=`<%l$T~&aTR~OY&[YZ#]Z;'S&[;'S;=`&p<%lO&[~&sP;=`<%l&[~&yVOY&vYZ'`Zy&vyz(cz;'S&v;'S;=`(w<%lO&v~'eTmQOy'tyz(Wz;'S't;'S;=`(]<%lO't~'wTOy'tyz(Wz;'S't;'S;=`(]<%lO't~(]OS~~(`P;=`<%l't~(hTS~OY!yYZ#]Z;'S!y;'S;=`#b<%lO!y~(zP;=`<%l&v~)SVU~OY!yYZ#]Z!Q!y!Q![(}![;'S!y;'S;=`#b<%lO!y~)lVOY)iYZ*RZ#P)i#P#Q(c#Q;'S)i;'S;=`+P<%lO)i~*WTmQO#P*g#P#Q(W#Q;'S*g;'S;=`*y<%lO*g~*jTO#P*g#P#Q(W#Q;'S*g;'S;=`*y<%lO*g~*|P;=`<%l*g~+SP;=`<%l)iR+YVOY!yYZ#]Z#X!y#X#Y+o#Y;'S!y;'S;=`#b<%lO!yR+rVOY!yYZ#]Z#U!y#U#V,X#V;'S!y;'S;=`#b<%lO!yR,[VOY!yYZ#]Z#i!y#i#j,q#j;'S!y;'S;=`#b<%lO!yR,tVOY!yYZ#]Z#Z!y#Z#[-Z#[;'S!y;'S;=`#b<%lO!yR-`ThPOY!yYZ#]Z;'S!y;'S;=`#b<%lO!yR-rVOY!yYZ#]Z#g!y#g#h.X#h;'S!y;'S;=`#b<%lO!yR.^TlPOY!yYZ#]Z;'S!y;'S;=`#b<%lO!yR.pZOY!yYZ#]Z#T!y#T#U-o#U#X!y#X#Y/c#Y#f!y#f#g0e#g;'S!y;'S;=`#b<%lO!yR/fVOY!yYZ#]Z#f!y#f#g/{#g;'S!y;'S;=`#b<%lO!yR0OVOY!yYZ#]Z#X!y#X#Y.X#Y;'S!y;'S;=`#b<%lO!yR0hVOY!yYZ#]Z#]!y#]#^0}#^;'S!y;'S;=`#b<%lO!yR1QVOY!yYZ#]Z#h!y#h#i1g#i;'S!y;'S;=`#b<%lO!yR1jVOY!yYZ#]Z#X!y#X#Y2P#Y;'S!y;'S;=`#b<%lO!yR2UTiPOY!yYZ#]Z;'S!y;'S;=`#b<%lO!yR2jTfPOY!yYZ#]Z;'S!y;'S;=`#b<%lO!y~2|VOY2yYZ3cZ#q2y#q#r(c#r;'S2y;'S;=`4a<%lO2y~3hTmQO#q3w#q#r(W#r;'S3w;'S;=`4Z<%lO3w~3zTO#q3w#q#r(W#r;'S3w;'S;=`4Z<%lO3w~4^P;=`<%l3w~4dP;=`<%l2y~4lOY~",
  tokenizers: [0, 1, Constant, Pronoun, output, listen, to],
  topRules: {"Program":[0,5]},
  tokenPrec: 144
})
