// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./rockstar-highlight.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#rO]QPOOPeOPOOOOQO'#Cf'#CfO]QPOOOmQPO'#CnQrQPOOOzQPO'#CmPOOO'#Cl'#ClPOOO)C>`)C>`OOQO-E6d-E6dO!YQPO,59YO`QPO'#ChQ!_QPOOQOQPOOO!dQPO,59XO`QPO'#CgOOQO1G.t1G.tOOQO,59S,59SOOQO-E6f-E6fOOQO-E6e-E6eOOQO,59R,59R",
  stateData: "!u~O_OSPPQQPQ~OSQOTSO~OPVOQVO~OUYO~OWZOX]O~OS_OWaXXaX]aX~OV`O~OWZO~OS_OWaaXaa]aa~OSW~",
  goto: "!YcPPPPPPPPPPdjpPPPvy!QQRORXRQ^URc^Q[TRb[RWPSTORRaZUUORZRd_",
  nodeNames: "⚠ LineComment BlockComment Program EOS Listen To VariableName EOB EOF",
  maxTerm: 18,
  propSources: [highlighting],
  skippedNodes: [0,1,2],
  repeatNodeCount: 3,
  tokenData: "'[~RZXYtYZ!P]^!mpqtst!sxy#b!n!o$P!}#O$t#h#i%^#o#p&m~~'V~yQ_~XYtpqt~!UQS~YZ![]^!g~!aQW~YZ![]^!g~!jPYZ![~!pPYZ!P~!vTOY!sYZ#VZ;'S!s;'S;=`#[<%lO!s~#[OP~~#_P;=`<%l!s~#eTOy#byz#tz;'S#b;'S;=`#y<%lO#b~#yOQ~~#|P;=`<%l#b~$SP#]#^$V~$YP#g#h$]~$`P#h#i$c~$fP#X#Y$i~$lP#b#c$o~$tOT~~$wTO#P$t#P#Q#t#Q;'S$t;'S;=`%W<%lO$t~%ZP;=`<%l$t~%aQ#[#]%g#c#d&h~%jP#X#Y%m~%pPpq%s~%vP#g#h%y~%|P#c#d&P~&SP#i#j&V~&YP#b#c&]~&`P#W#X&c~&hOV~~&mOU~~&pTO#q&m#q#r#t#r;'S&m;'S;=`'P<%lO&m~'SP;=`<%l&m~'[OX~",
  tokenizers: [0],
  topRules: {"Program":[0,3]},
  tokenPrec: 80
})
