// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Constant = 1,
  Pronoun = 2,
  output = 16,
  listen = 17,
  to = 18,
  LineComment = 3,
  BlockComment = 4,
  Program = 5,
  Number = 6,
  String = 7,
  VariableName = 8,
  EOS = 9,
  EOF = 10
