// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  OutputToken = 1,
  LineComment = 2,
  BlockComment = 3,
  Program = 4,
  EOS = 5,
  Listen = 6,
  To = 7,
  VariableName = 8,
  EOB = 9,
  EOF = 10
