name: build-wasm-and-linux-binaries
on:
  push:
    branches: ["main"]
    paths:
  #     - 'Starship/**'
      - '.github/workflows/build-wasm-and-linux-binaries.yml'
  workflow_dispatch:
  workflow_call:
concurrency:
  group: "build-wasm-and-linux-binaries"
  cancel-in-progress: true
jobs:
  build-engine:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v4
      # - name: Set up .NET 8 SDK
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '8.x'
      # - name: Install .NET WASM workloads
      #   working-directory: ./Starship
      #   run: dotnet workload install wasm-tools
      # - name: Build Rockstar
      #   run: dotnet build Starship -c Release
      # - name: Test Rockstar
      #   run: dotnet test Starship -c Release
      # - name: dotnet publish WASM engine
      #   run: dotnet publish Starship/Rockstar.Wasm -o rockstar-wasm-binary -c Release
      # - name: dotnet publish Linux binary
      #   run: dotnet publish Starship/Rockstar -o rockstar-linux-x64-binary -c Release
      # - uses: actions/cache@v4
      #   name: save WASM binary to cache
      #   id: save-rockstar-wasm-binary-to-cache
      #   with:
      #     enableCrossOsArchive: true
      #     path: rockstar-wasm-binary
      #     key: rockstar-wasm-binary-${{ github.run_id }}
      #     restore-keys: |
      #       rockstar-wasm-binary
      - name: Fake a build
        run: |
          mkdir rockstar-linux-x64-binary
          echo "rockstar" > rockstar-linux-x64-binary/rockstar.txt
          mkdir rockstar-wasm-binary
          echo "rockstar" > rockstar-wasm-binary/rockstar.txt
      - uses: actions/cache/save@v4
        name: save Linux x64 binary to cache
        id: save-rockstar-linux-x64-binary-to-cache
        with:
          enableCrossOsArchive: true
          path: rockstar-linux-x64-binary
          key: rockstar-linux-x64-binary-${{ github.run_id }}
      - uses: actions/cache/save@v4
        name: save Linux x64 binary to cache
        id: save-rockstar-wasm-binary-to-cache
        with:
          enableCrossOsArchive: true
          path: rockstar-wasm-binary
          key: rockstar-wasm-binary-${{ github.run_id }}
  rockstar-macos-binary:
    needs: build-engine
    uses: ./.github/workflows/build-macos-binary.yml
  rockstar-windows-binary:
    needs: build-engine
    uses: ./.github/workflows/build-windows-binary.yml
