name: build-windows-binary
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: dotnet publish Windows binary
        run: dotnet publish Starship/Rockstar -o rockstar-windows-binary -c Release
      - uses: actions/cache/save@v3
        name: save Windows binary to cache
        id: save-rockstar-windows-binary-to-cache
        with:
          path: rockstar-windows-binary
          key: rockstar-windows-binary
