name: build-macos-binary
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      - name: "Display build version"
        run: echo "tag ${{ steps.semver.outputs.next }}"
      - name: Patch VERSION constant inside Starship/Rockstar/Program.cs
        run: sed -i "" 's/__VERSION__/${{ steps.semver.outputs.next }}/g' Starship/Rockstar/Program.cs
      - name: dotnet publish macos x64 binary
        run: dotnet publish Starship/Rockstar -o rockstar-macos-x64-binary -r osx-x64 -c Release
      - name: dotnet publish macos ARM64 binary
        run: dotnet publish Starship/Rockstar -o rockstar-macos-arm64-binary -r osx-arm64 -c Release
      - name: Test ARM64 binary
        run:
          rockstar-macos-arm64-binary/rockstar --version
      - uses: actions/cache/save@v4
        name: Save rockstar-macos-x64-binary to cache
        id: save-rockstar-macos-x64-binary-to-cache
        with:
          enableCrossOsArchive: true
          path: rockstar-macos-x64-binary
          key: rockstar-macos-x64-binary-${{ github.run_id }}
      - uses: actions/cache/save@v4
        name: Save rockstar-macos-arm64-binary to cache
        id: save-rockstar-macos-arm64-binary-to-cache
        with:
          enableCrossOsArchive: true
          path: rockstar-macos-arm64-binary
          key: rockstar-macos-arm64-binary-${{ github.run_id }}
