name: build-macos-binary
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: dotnet publish macos binary
        run: dotnet publish Starship/Rockstar -o rockstar-macos-binary -c Release
      - uses: actions/cache/save@v3
        name: Save macOS binary to cache
        id: save-rockstar-macos-binary-to-cache
        with:
          path: rockstar-macos-binary
          key: rockstar-macos-binary
