name: build-windows-binary
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      - name: "Display build version"
        run: echo "tag ${{ steps.semver.outputs.next }}"
      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
#      - name: Patch VERSION constant inside Starship/Rockstar/Program.cs
#        run: (Get-content Starship/Rockstar/Program.cs) | Foreach-Object {$_ -replace "__VERSION__", "${{ steps.semver.outputs.next }}"} | Set-Content Starship/Rockstar/Program.cs
      - name: dotnet publish Windows x64 binary
        run: dotnet publish Starship/Rockstar -o rockstar-windows-x64-binary -c Release
      - name: Test Windows x64 binary
        run:
          rockstar-windows-x64-binary/rockstar.exe --version
      - uses: actions/cache/save@v4
        name: save rockstar-windows-x64-binary to cache
        id: save-rockstar-windows-x64-binary-to-cache
        with:
          enableCrossOsArchive: true
          path: rockstar-windows-x64-binary
          key: rockstar-windows-x64-binary-${{ github.run_id }}
