name: cache-test
on:
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/cache-test.yml'
  workflow_dispatch:
jobs:
  cache-some-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: MAKE UP SOME FILES
        run: |
          mkdir my-files
          echo "This is some stuff" > my-files/file0001.txt
          echo "This is some stuff" > my-files/file0002.txt
          echo "This is some stuff" > my-files/file0003.txt
          echo "This is some stuff" > my-files/file0004.txt
          ls -lR
      - uses: actions/cache/save@v4
        id: put-files-in-cache
        with:
          path: my-files
          key: my-cached-files-${{ github.run_id }}
  fetch-stuff-from-cache-1:
    runs-on: ubuntu-latest
    steps:
      - name: restore files from from cache
        uses: actions/cache/restore@v4
        with:
          path: my-files
          key: my-cached-files
          restore-keys: |
            my-cached-files-
            my-cached-files
            another-restore-key
      - name: see what we got
        run: ls -lR
  fetch-stuff-from-cache-2:
    runs-on: ubuntu-latest
    steps:
      - name: restore files from from cache
        uses: actions/cache/restore@v4
        with:
          path: my-files
          key: my-cached-files-${{ github.run_id }}
          restore-keys: |
            my-cached-files-
            my-cached-files
            another-restore-key
      - name: see what we got
        run: ls -lR
  fetch-stuff-from-cache-3:
    runs-on: ubuntu-latest
    steps:
      - name: restore files from from cache
        uses: actions/cache/restore@v4
        with:
          path: my-files
          key: another-restore-key
          restore-keys: |
            my-cached-files-
            my-cached-files
            another-restore-key
      - name: see what we got
        run: ls -lR
