name: Deploy Jekyll site to Pages
on:
  # Run after the engine is rebuilt
  # workflow_run:
  #   workflows: ['build-rockstar-engine']
  #   types: [completed]
  #   branches: ['main']
  # # Run after any website source files are changed
  # push:
  #   branches: ["main"]
  #   paths:
  #     - 'codewithrockstar.com/**'
  #     - '.github/workflows/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  rockstar-engine:
    uses: ./.github/workflows/build-rockstar-engine.yml
  rockstar-macos-binary:
    uses: ./.github/workflows/build-macos-binary.yml
  rockstar-windows-binary:
    uses: ./.github/workflows/build-windows-binary.yml
  build-docs-site:
    runs-on: ubuntu-latest
    needs: rockstar-engine
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download WASM engine for codewithrockstar.com
        uses: actions/download-artifact@v4
        with:
          name: rockstar_wasm
          path: ./docs.codewithrockstar.com/wasm/wwwroot/_framework
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
          working-directory: ./docs.codewithrockstar.com
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        with:
          working-directory: ./docs.codewithrockstar.com
      - name: Build docs.codewithrockstar.com site
        # Outputs to the './_site' directory by default
        working-directory: ./docs.codewithrockstar.com
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload docs.codewithrockstar.com_site
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
        with:
          name: docs.codewithrockstar.com_site
          path: ./docs.codewithrockstar.com/_site

  # Build job
  build-main-site:
    runs-on: ubuntu-latest
    needs: [rockstar-engine, rockstar-macos-binary, rockstar-windows-binary]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download WASM engine for codewithrockstar.com
        uses: actions/download-artifact@v4
        with:
          name: rockstar_wasm
          path: ./codewithrockstar.com/wasm/wwwroot/_framework
      - name: Download macOS binary for codewithrockstar.com
        uses: actions/download-artifact@v4
        with:
          name: rockstar_macos_binary
          path: ./codewithrockstar.com/download/macos
      - name: Download Windows binary for codewithrockstar.com
        uses: actions/download-artifact@v4
        with:
          name: rockstar_windows_binary
          path: ./codewithrockstar.com/download/windows
      - name: Download Linux binary for codewithrockstar.com
        uses: actions/download-artifact@v4
        with:
          name: rockstar_linux_binary
          path: ./codewithrockstar.com/download/linux
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
          working-directory: ./codewithrockstar.com
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        with:
          working-directory: ./codewithrockstar.com
      - name: Build codewithrockstar.com site
        # Outputs to the './_site' directory by default
        working-directory: ./codewithrockstar.com
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./codewithrockstar.com/_site
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-main-site
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
