name: restore-things-from-cache
on:
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/restore-things-from-cache.yml'
  workflow_dispatch:
jobs:
  fetch-stuff-from-cache-1:
    runs-on: ubuntu-latest
    steps:
      - name: restore dylan-test-alpha-cache- from cache (no restore-keys)
        uses: actions/cache/restore@v4
        with:
          path: dylan-test-alpha
          key: dylan-test-alpha-cache-
      - name: see what we got
        run: ls -lR
  fetch-stuff-from-cache-3:
    runs-on: ubuntu-latest
    steps:
      - name: restore files from from cache
        uses: actions/cache/restore@v4
        with:
          path: dylan-test-alpha
          key: this-key-does-not-match-anything
          restore-keys: |
            dylan-test-alpha-cache-
      - name: see what we got
        run: ls -lR
  fetch-stuff-from-cache-4:
    runs-on: ubuntu-latest
    steps:
      - name: restore files from from cache
        uses: actions/cache/restore@v4
        with:
          path: dylan-test-alpha
          key: this-key-does-not-match-anything
          restore-keys: |
            dylan-test-alpha-cache
      - name: see what we got
        run: ls -lR
